ALTER TABLE public.doctor_recommendation_reviews
    ADD COLUMN is_final_decision boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX uq_doctor_review_run
    ON public.doctor_recommendation_reviews (run_id);

CREATE UNIQUE INDEX uq_doctor_review_final_episode
    ON public.doctor_recommendation_reviews (episode_id)
    WHERE is_final_decision;

CREATE TABLE public.doctor_final_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL UNIQUE
        REFERENCES public.doctor_recommendation_reviews(id) ON DELETE CASCADE,
    diagnosis_json jsonb NOT NULL,
    surgery_plan_json jsonb,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.pharmacist_final_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL UNIQUE
        REFERENCES public.doctor_recommendation_reviews(id) ON DELETE CASCADE,
    systemic_antibiotic_plan_json jsonb,
    local_antibiotic_plan_json jsonb,
    sensitivity_results_json jsonb,
    notes text,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO public.doctor_final_decisions (
    review_id,
    diagnosis_json,
    surgery_plan_json,
    created_by,
    updated_by,
    created_at,
    updated_at
)
SELECT
    id,
    doctor_diagnosis_json,
    modification_json -> 'surgery',
    created_by,
    updated_by,
    created_at,
    updated_at
FROM public.doctor_recommendation_reviews
WHERE doctor_diagnosis_json IS NOT NULL;

INSERT INTO public.pharmacist_final_decisions (
    review_id,
    systemic_antibiotic_plan_json,
    local_antibiotic_plan_json,
    created_by,
    updated_by,
    created_at,
    updated_at
)
SELECT
    id,
    modification_json -> 'systemicAntibiotic',
    modification_json -> 'localAntibiotic',
    created_by,
    updated_by,
    created_at,
    updated_at
FROM public.doctor_recommendation_reviews
WHERE modification_json ? 'systemicAntibiotic'
   OR modification_json ? 'localAntibiotic';

INSERT INTO public.permissions (name, api_path, method, module)
SELECT permission.name, permission.api_path, permission.method, 'DOCTOR_REVIEWS'
FROM (VALUES
    ('Get final decision by episode', '/api/v1/episodes/{episodeId}/doctor-reviews/final-decision', 'GET'),
    ('Select final decision version', '/api/v1/episodes/{episodeId}/doctor-reviews/{reviewId}/final-decision', 'PUT'),
    ('Save pharmacist final decision', '/api/v1/doctor-reviews/{reviewId}/pharmacist-final-decision', 'PUT')
) AS permission(name, api_path, method)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.permissions existing
    WHERE existing.api_path = permission.api_path
      AND existing.method = permission.method
);

WITH doctor_review_roles AS (
    SELECT DISTINCT role_permission.role_id
    FROM public.role_permissions role_permission
    JOIN public.permissions permission ON permission.id = role_permission.permission_id
    WHERE permission.module = 'DOCTOR_REVIEWS'
), final_decision_permissions AS (
    SELECT id
    FROM public.permissions
    WHERE api_path IN (
        '/api/v1/episodes/{episodeId}/doctor-reviews/final-decision',
        '/api/v1/episodes/{episodeId}/doctor-reviews/{reviewId}/final-decision',
        '/api/v1/doctor-reviews/{reviewId}/pharmacist-final-decision'
    )
)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT role.role_id, permission.id
FROM doctor_review_roles role
CROSS JOIN final_decision_permissions permission
ON CONFLICT DO NOTHING;
