-- A recommendation run owns one immutable backend rule-engine diagnosis built
-- from the same clinical snapshot. Treatment recommendations remain in
-- ai_recommendation_items; diagnosis is not an AI recommendation category.
CREATE TABLE "public"."rule_based_diagnostic_results" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" bigint NOT NULL UNIQUE,
    "title" character varying(500) NOT NULL,
    "item_json" jsonb NOT NULL,
    "assessment_json" jsonb NOT NULL,
    "explanation_json" jsonb NOT NULL,
    "warnings_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp without time zone,
    "created_by" character varying(255),
    "updated_by" character varying(255),
    CONSTRAINT "rule_based_diagnostic_results_run_id_fkey"
        FOREIGN KEY ("run_id") REFERENCES "public"."ai_recommendation_runs"("id") ON DELETE CASCADE
);

CREATE INDEX "idx_rule_diagnostic_run_id"
    ON "public"."rule_based_diagnostic_results" ("run_id");

-- Older releases stored the backend diagnosis as a DIAGNOSTIC_TEST item and
-- duplicated assessment/explanation on the run. Pick one legacy diagnostic per
-- run deterministically and retain its audit metadata.
INSERT INTO "public"."rule_based_diagnostic_results" (
    "run_id",
    "title",
    "item_json",
    "assessment_json",
    "explanation_json",
    "warnings_json",
    "created_at",
    "updated_at",
    "created_by",
    "updated_by"
)
SELECT DISTINCT ON (item."run_id")
    item."run_id",
    item."title",
    item."item_json",
    COALESCE(run."assessment_json", '{}'::jsonb),
    COALESCE(run."explanation_json", '{}'::jsonb),
    COALESCE(
        item."item_json" #> '{ai_reasoning,warnings}',
        item."item_json" #> '{aiReasoning,warnings}',
        '[]'::jsonb
    ),
    item."created_at",
    item."updated_at",
    item."created_by",
    item."updated_by"
FROM "public"."ai_recommendation_items" item
JOIN "public"."ai_recommendation_runs" run ON run."id" = item."run_id"
WHERE item."category" = 'DIAGNOSTIC_TEST'
ORDER BY item."run_id", item."priority_order", item."id";

-- Historical run warnings were conditionally owned by either the backend rule
-- engine or Rag_Agentic. Clear only values that can be proven to be the same
-- diagnostic warning payload; retain all other values as potential RAG output.
UPDATE "public"."ai_recommendation_runs" run
SET "warnings_json" = '[]'::jsonb
FROM "public"."rule_based_diagnostic_results" diagnostic
WHERE diagnostic."run_id" = run."id"
  AND COALESCE(run."warnings_json", '[]'::jsonb) = diagnostic."warnings_json";

-- Citations attached to a legacy diagnostic item cascade with the item. They
-- were synthetic backend citations rather than RAG evidence for treatment.
DELETE FROM "public"."ai_recommendation_items"
WHERE "category" = 'DIAGNOSTIC_TEST';

DROP INDEX IF EXISTS "public"."idx_ai_runs_assessment_gin";

ALTER TABLE "public"."ai_recommendation_runs"
    DROP COLUMN "assessment_json",
    DROP COLUMN "explanation_json";

ALTER TABLE "public"."ai_recommendation_items"
    ADD CONSTRAINT "ai_recommendation_items_treatment_category_check"
    CHECK ("category" IN (
        'SYSTEMIC_ANTIBIOTIC',
        'SURGERY_PROCEDURE',
        'LOCAL_ANTIBIOTIC'
    ));
