ALTER TABLE public.doctor_final_decisions
    ADD COLUMN run_id bigint,
    ADD COLUMN author_user_id bigint,
    ADD COLUMN status character varying(20) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN signed_at timestamp with time zone,
    ADD COLUMN version_no bigint NOT NULL DEFAULT 0;

UPDATE public.doctor_final_decisions decision
SET run_id = review.run_id
FROM public.doctor_recommendation_reviews review
WHERE review.id = decision.review_id;

UPDATE public.doctor_final_decisions decision
SET author_user_id = (
    SELECT app_user.id
    FROM public.users app_user
    WHERE lower(app_user.email) = lower(decision.created_by)
    ORDER BY app_user.id
    LIMIT 1
)
WHERE decision.author_user_id IS NULL;

ALTER TABLE public.doctor_final_decisions
    ALTER COLUMN run_id SET NOT NULL,
    ADD CONSTRAINT fk_doctor_decision_run
        FOREIGN KEY (run_id) REFERENCES public.ai_recommendation_runs(id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_doctor_decision_author
        FOREIGN KEY (author_user_id) REFERENCES public.users(id) ON DELETE RESTRICT,
    ADD CONSTRAINT chk_doctor_decision_status
        CHECK (status IN ('DRAFT', 'SIGNED'));

CREATE UNIQUE INDEX uq_doctor_decision_run
    ON public.doctor_final_decisions (run_id);

CREATE INDEX idx_doctor_decision_author
    ON public.doctor_final_decisions (author_user_id);

-- Preserve the meaning of a legacy final review: it was already accepted by
-- its doctor, so the migrated doctor lane must be immutable as well.
UPDATE public.doctor_final_decisions decision
SET status = 'SIGNED',
    signed_at = COALESCE(decision.signed_at, review.updated_at, review.created_at)
FROM public.doctor_recommendation_reviews review
WHERE review.id = decision.review_id
  AND review.is_final_decision = true;

CREATE TABLE public.pharmacist_final_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL UNIQUE
        REFERENCES public.ai_recommendation_runs(id) ON DELETE CASCADE,
    author_user_id bigint NOT NULL
        REFERENCES public.users(id) ON DELETE RESTRICT,
    status character varying(20) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'SIGNED')),
    systemic_antibiotic_plan_json jsonb,
    local_antibiotic_plan_json jsonb,
    notes text,
    signed_at timestamp with time zone,
    version_no bigint NOT NULL DEFAULT 0,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_pharmacist_decision_author
    ON public.pharmacist_final_decisions (author_user_id);

CREATE TABLE public.recommendation_final_selections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id bigint NOT NULL UNIQUE
        REFERENCES public.pji_episodes(id) ON DELETE CASCADE,
    run_id bigint NOT NULL UNIQUE
        REFERENCES public.ai_recommendation_runs(id) ON DELETE CASCADE,
    selected_by_user_id bigint NOT NULL
        REFERENCES public.users(id) ON DELETE RESTRICT,
    selected_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_no bigint NOT NULL DEFAULT 0,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_recommendation_final_selection_user
    ON public.recommendation_final_selections (selected_by_user_id);

INSERT INTO public.recommendation_final_selections (
    episode_id,
    run_id,
    selected_by_user_id,
    selected_at,
    created_by,
    created_at,
    updated_at
)
SELECT
    review.episode_id,
    review.run_id,
    decision.author_user_id,
    COALESCE(decision.signed_at, review.updated_at, review.created_at),
    review.updated_by,
    COALESCE(review.updated_at, review.created_at),
    COALESCE(review.updated_at, review.created_at)
FROM public.doctor_recommendation_reviews review
JOIN public.doctor_final_decisions decision ON decision.review_id = review.id
WHERE review.is_final_decision = true
  AND decision.author_user_id IS NOT NULL
ON CONFLICT (episode_id) DO NOTHING;

INSERT INTO public.roles (name, description, active, created_by, created_at, updated_at)
SELECT 'PHARMACIST', 'Dược sĩ lâm sàng', true, 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM public.roles WHERE upper(name) = 'PHARMACIST'
);

INSERT INTO public.permissions (name, api_path, method, module)
SELECT permission.name, permission.api_path, permission.method, 'CLINICAL_DECISIONS'
FROM (VALUES
    ('Get clinical decision workspace', '/api/v1/episodes/{episodeId}/clinical-decisions/workspace', 'GET'),
    ('Get run clinical decisions', '/api/v1/ai-recommendations/runs/{runId}/clinical-decisions', 'GET'),
    ('Save doctor decision', '/api/v1/ai-recommendations/runs/{runId}/doctor-decision', 'PUT'),
    ('Sign doctor decision', '/api/v1/ai-recommendations/runs/{runId}/doctor-decision/sign', 'POST'),
    ('Save pharmacist decision', '/api/v1/ai-recommendations/runs/{runId}/pharmacist-decision', 'PUT'),
    ('Sign pharmacist decision', '/api/v1/ai-recommendations/runs/{runId}/pharmacist-decision/sign', 'POST'),
    ('Select final recommendation run', '/api/v1/episodes/{episodeId}/clinical-decisions/final-run/{runId}', 'PUT')
) AS permission(name, api_path, method)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.permissions existing
    WHERE existing.api_path = permission.api_path
      AND existing.method = permission.method
);

WITH target_roles AS (
    SELECT id, upper(name) AS role_name
    FROM public.roles
    WHERE upper(name) IN ('DOCTOR', 'PHARMACIST', 'ADMIN', 'SUPER_ADMIN')
), target_permissions AS (
    SELECT id, api_path
    FROM public.permissions
    WHERE module = 'CLINICAL_DECISIONS'
)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM target_roles role
CROSS JOIN target_permissions permission
WHERE permission.api_path LIKE '%/workspace'
   OR permission.api_path LIKE '%/clinical-decisions'
   OR (role.role_name IN ('DOCTOR', 'ADMIN', 'SUPER_ADMIN')
       AND (permission.api_path LIKE '%/doctor-decision%'
            OR permission.api_path LIKE '%/final-run/%'))
   OR (role.role_name IN ('PHARMACIST', 'ADMIN', 'SUPER_ADMIN')
       AND permission.api_path LIKE '%/pharmacist-decision%')
ON CONFLICT DO NOTHING;

WITH pharmacist_role AS (
    SELECT id FROM public.roles WHERE upper(name) = 'PHARMACIST'
), readable_permissions AS (
    SELECT id
    FROM public.permissions
    WHERE method = 'GET'
      AND api_path IN (
          '/api/v1/patients',
          '/api/v1/patients/{id}',
          '/api/v1/patients/{patientId}/episodes',
          '/api/v1/episodes/{id}',
          '/api/v1/episodes/{id}/full',
          '/api/v1/episodes/{episodeId}/ai-recommendations/runs',
          '/api/v1/ai-recommendations/runs/{runId}'
      )
)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM pharmacist_role role
CROSS JOIN readable_permissions permission
ON CONFLICT DO NOTHING;
