CREATE TABLE "public"."recommendation_job_outbox" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "run_id" bigint NOT NULL,
    "payload_json" jsonb NOT NULL,
    "attempt_count" integer DEFAULT 0 NOT NULL,
    "available_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "last_error" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp without time zone,
    "created_by" character varying(255),
    "updated_by" character varying(255),
    CONSTRAINT "recommendation_job_outbox_attempt_count_check"
        CHECK ("attempt_count" >= 0),
    CONSTRAINT "recommendation_job_outbox_run_id_fkey"
        FOREIGN KEY ("run_id") REFERENCES "public"."ai_recommendation_runs"("id") ON DELETE CASCADE
);

CREATE INDEX "idx_recommendation_job_outbox_ready"
    ON "public"."recommendation_job_outbox" ("available_at", "id");

CREATE INDEX "idx_recommendation_job_outbox_run_id"
    ON "public"."recommendation_job_outbox" ("run_id");
